#!/bin/sh
rm -rf component.xml
rm -rf parallella.bit.bin
rm -rf parallella_mio.cache
rm -rf parallella_mio.hw
rm -rf parallella_mio.sim
rm -rf parallella_mio.xpr
rm -rf parallella_mio.zip
rm -rf reports
rm -rf results
rm -rf src
rm -rf system.cache
rm -rf system.hw
rm -rf system.runs
rm -rf system.sim
rm -rf system.srcs
rm -rf system_wrapper.bit.bin
rm -rf system.xpr
rm -rf vivado*.jou
rm -rf vivado*.log
rm -rf xgui
