.PHONY: all clean

all:
	make -C ../../adi all
	make -C parallella_base/ all
	make -C headless_e16_z7010/ all
	make -C headless_e16_z7020/ all
	make -C hdmi_e16_z7010/ all
	make -C hdmi_e16_z7020/ all

clean:
	make -C ../../adi clean
	make -C parallella_base/ clean
	make -C headless_e16_z7010/ clean
	make -C headless_e16_z7020/ clean
	make -C hdmi_e16_z7010/ clean
	make -C hdmi_e16_z7020/ clean
